const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"分享类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFenxiang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"回访类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuifang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"流浪动物类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLiulangdongwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"动物品种管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLiulangdongwuPinzhong"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"流浪动物管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"流浪动物留言管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"流浪动物收藏管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "查看",
                            "删除"
                        ],
                        "menu":"流浪动物领养申请管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuOrder"
                    }
                ],
                "menu":"流浪动物管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宠物分享管理",
                        "menuJump":"列表",
                        "tableName":"fenxiang"
                    }
                ],
                "menu":"宠物分享管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"回访管理",
                        "menuJump":"列表",
                        "tableName":"huifang"
                    }
                ],
                "menu":"回访管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"业主管理",
                        "menuJump":"列表",
                        "tableName":"yezhu"
                    }
                ],
                "menu":"业主管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"志愿者管理",
                        "menuJump":"列表",
                        "tableName":"zhiyuanzhe"
                    }
                ],
                "menu":"志愿者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"流浪动物管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"流浪动物留言管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"流浪动物收藏管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"流浪动物领养申请管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuOrder"
                    }
                ],
                "menu":"流浪动物管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"宠物分享管理",
                        "menuJump":"列表",
                        "tableName":"fenxiang"
                    }
                ],
                "menu":"宠物分享管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"业主",
        "tableName":"yezhu"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"流浪动物管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"流浪动物留言管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"流浪动物收藏管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "审核",
                            "查看"
                        ],
                        "menu":"流浪动物领养申请管理",
                        "menuJump":"列表",
                        "tableName":"liulangdongwuOrder"
                    }
                ],
                "menu":"流浪动物管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"宠物分享管理",
                        "menuJump":"列表",
                        "tableName":"fenxiang"
                    }
                ],
                "menu":"宠物分享管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"回访管理",
                        "menuJump":"列表",
                        "tableName":"huifang"
                    }
                ],
                "menu":"回访管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"志愿者",
        "tableName":"zhiyuanzhe"
    }
]
    }
}
export default menu;
